version: '3'

#VOLUMES
# volumes:
#   my-dir:
#     dirver

#NETWORK
networks:
  web-net:
    external: true

#SERVICES
services:
  fmsphuongdong_spa:
    hostname: fmsphuongdong_spa
    container_name: fmsphuongdong_spa
    image: vanquyenktktbd/fmsphuongdong_spa:uat
    build: .
    restart: always
    networks:
      - web-net
    ports:
      - 5200:80
